#!/usr/bin/env python
"""Generate LaTeX tables + inline-number macros from the committed metrics.

Writing the paper's numbers from a script (rather than typing them) guarantees the
manuscript can never silently disagree with ``results/metrics/``. Produces:

    paper/results_macros.tex  \newcommand macros for inline figures in the prose
    paper/tables.tex          the main results table (+ per-class table for the best model)

Usage:
    uv run python scripts/make_paper_tables.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from papavision import CLASS_LABELS  # noqa: E402
from papavision.utils import METRICS_DIR, ROOT, get_logger, load_json  # noqa: E402

log = get_logger()
PAPER = ROOT / "paper"

MODEL_ORDER = ["custom_cnn", "mobilenet_v2", "resnet18", "efficientnet_b0"]
PRETTY = {
    "custom_cnn": "Custom CNN (scratch)",
    "mobilenet_v2": "MobileNetV2",
    "resnet18": "ResNet-18",
    "efficientnet_b0": "EfficientNet-B0",
}
# Macro-name stems (LaTeX command names must be letters only — no digits/underscores).
MACRO = {
    "custom_cnn": "Custom",
    "mobilenet_v2": "Mobilenet",
    "resnet18": "Resnet",
    "efficientnet_b0": "Efficientnet",
}


def fmt_pm(mean: float, std: float, pct: bool = True) -> str:
    """Format mean ± std, as a percentage by default."""
    if pct:
        return f"{mean * 100:.1f}\\,$\\pm$\\,{std * 100:.1f}"
    return f"{mean:.3f}\\,$\\pm$\\,{std:.3f}"


def num_macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main() -> None:
    summary = load_json(METRICS_DIR / "summary.json")
    models = summary["models"]

    # Pull dataset sizes from any per-run test metric / run record.
    run_files = sorted((METRICS_DIR / "runs").glob("*.json"))
    run_files = [p for p in run_files if not p.name.startswith(("hpo_", "_")) and "_smoke" not in p.name]
    meta = load_json(run_files[0])["meta"] if run_files else {}

    present = [m for m in MODEL_ORDER if m in models]

    # ---- results_macros.tex -------------------------------------------------
    macros = ["% Auto-generated by scripts/make_paper_tables.py — do not edit.\n"]
    for m in present:
        s = models[m]
        stem = MACRO[m]
        macros.append(num_macro(f"acc{stem}", f"{s['accuracy_mean'] * 100:.1f}"))
        macros.append(num_macro(f"fone{stem}", f"{s['macro_f1_mean'] * 100:.1f}"))
        macros.append(num_macro(f"ece{stem}", f"{s['ece_mean']:.3f}"))
        macros.append(num_macro(f"params{stem}", f"{s['params']['total']:,}".replace(",", "{,}")))
        macros.append(num_macro(f"trainparams{stem}", f"{s['params']['trainable']:,}".replace(",", "{,}")))

    # Dataset macros.
    if meta:
        macros.append(num_macro("ntrain", str(meta.get("n_train", "?"))))
        macros.append(num_macro("nval", str(meta.get("n_val", "?"))))
        macros.append(num_macro("ntest", str(meta.get("n_test", "?"))))
        macros.append(num_macro("ntotal", str(meta.get("n_total", "?"))))
        macros.append(num_macro("nseeds", str(models[present[0]]["n_seeds"])))

    # Best model by macro-F1.
    best_model = max(present, key=lambda m: models[m]["macro_f1_mean"])
    macros.append(num_macro("bestmodel", PRETTY[best_model]))
    macros.append(num_macro("bestfone", f"{models[best_model]['macro_f1_mean'] * 100:.1f}"))

    # Autoresearch winner.
    ar_path = METRICS_DIR / "autoresearch.json"
    if ar_path.exists():
        ar = load_json(ar_path)
        best = ar["best"]
        macros.append(num_macro("hpotrials", str(ar["trials"])))
        macros.append(num_macro("hpobestfone", f"{best['val_macro_f1'] * 100:.1f}"))
        hp = best["hyperparameters"]
        macros.append(num_macro("hpolr", f"{hp['lr']:g}"))
        macros.append(num_macro("hpowd", f"{hp['weight_decay']:g}"))
        macros.append(num_macro("hpowidth", str(hp["width"])))
        macros.append(num_macro("hpodropout", f"{hp['dropout']:g}"))
        macros.append(num_macro("hpoaug", f"{hp['aug_strength']:g}"))

    # McNemar: custom_cnn vs the best transfer model (clean macros for the prose).
    mcnemar = summary.get("mcnemar", {})
    transfer = [m for m in present if m != "custom_cnn"]
    if transfer:
        best_transfer = max(transfer, key=lambda m: models[m]["macro_f1_mean"])
        macros.append(num_macro("besttransfer", PRETTY[best_transfer]))
        macros.append(num_macro("besttransferfone", f"{models[best_transfer]['macro_f1_mean'] * 100:.1f}"))
        # Parameter ratio range: custom CNN vs smallest & largest transfer model.
        cust_p = models["custom_cnn"]["params"]["total"] if "custom_cnn" in models else 1
        tparams = [models[m]["params"]["total"] for m in transfer]
        macros.append(num_macro("paramratiomin", f"{min(tparams) / cust_p:.0f}"))
        macros.append(num_macro("paramratiomax", f"{max(tparams) / cust_p:.0f}"))
        for key, res in mcnemar.items():
            if "custom_cnn" in key and best_transfer in key:
                p = res["p_value"]
                verdict = "no significant difference" if p >= 0.05 else "a significant difference"
                macros.append(num_macro("mcnemarbestp", f"{p:.3g}"))
                macros.append(num_macro("mcnemarbestverdict", verdict))

    (PAPER / "results_macros.tex").write_text("".join(macros))
    log.info("Wrote paper/results_macros.tex (%d macros)", len(macros) - 1)

    # ---- tables.tex ---------------------------------------------------------
    lines = ["% Auto-generated by scripts/make_paper_tables.py — do not edit.\n"]
    lines.append("\\begin{table}[t]\n\\centering\n")
    lines.append("\\caption{Test-set performance on the held-out potato leaf split "
                 f"($n={meta.get('n_test', '?')}$ images), reported as mean\\,$\\pm$\\,"
                 f"standard deviation over {models[present[0]]['n_seeds']} random seeds. "
                 "Accuracy and macro-F1 are percentages; ECE is the expected calibration "
                 "error (lower is better). Params = total parameters.}\n")
    lines.append("\\label{tab:results}\n")
    lines.append("\\begin{tabular}{lrccc}\n\\hline\n")
    lines.append("Model & Params & Accuracy (\\%) & Macro-F1 (\\%) & ECE \\\\\n\\hline\n")
    for m in present:
        s = models[m]
        pstr = f"{s['params']['total']:,}".replace(",", "{,}")  # LaTeX-safe thousands
        bold = "\\textbf" if m == best_model else ""
        lines.append(
            f"{PRETTY[m]} & {pstr} & "
            f"{fmt_pm(s['accuracy_mean'], s['accuracy_std'])} & "
            f"{bold}{{{fmt_pm(s['macro_f1_mean'], s['macro_f1_std'])}}} & "
            f"{s['ece_mean']:.3f} \\\\\n"
        )
    lines.append("\\hline\n\\end{tabular}\n\\end{table}\n")

    # Per-class table for the best model (use its representative seed-0 run).
    test_files = sorted((METRICS_DIR / "test").glob(f"{best_model}_seed*.json"))
    test_files = [p for p in test_files if "_smoke" not in p.name]
    if test_files:
        r = load_json(test_files[0])
        pc = r["per_class"]
        lines.append("\n\\begin{table}[t]\n\\centering\n")
        lines.append(f"\\caption{{Per-class test metrics for the best model "
                     f"({PRETTY[best_model]}, representative seed). "
                     "Support is the number of test images per class.}\n")
        lines.append("\\label{tab:perclass}\n")
        lines.append("\\begin{tabular}{lcccc}\n\\hline\n")
        lines.append("Class & Precision & Recall & F1 & Support \\\\\n\\hline\n")
        for cls in CLASS_LABELS:
            d = pc[cls]
            lines.append(f"{cls} & {d['precision']:.3f} & {d['recall']:.3f} & "
                         f"{d['f1']:.3f} & {d['support']} \\\\\n")
        lines.append("\\hline\n\\end{tabular}\n\\end{table}\n")

    (PAPER / "tables.tex").write_text("".join(lines))
    log.info("Wrote paper/tables.tex")


if __name__ == "__main__":
    main()
